name: Sync-Images
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      srcImage:
        description: 'Source Image To Sync'
        required: true
        default: '-'
      destImage:
        description: 'Dest Image Name'
        required: true
        default: '-'
jobs:
  syncImages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        src_image=${{ github.event.inputs.srcImage }}
        dest_image=${{ github.event.inputs.destImage }}
        skopeo copy docker://docker.io/${src_image} docker://registry.cn-hangzhou.aliyuncs.com/dalianmao/${dest_image}
        #chmod +x  $GITHUB_WORKSPACE/scripts/copy-images.sh
        #$GITHUB_WORKSPACE/scripts/copy-images.sh $repo_images