name: Sync-Images
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      srcImage:
        description: '需同步镜像,多个镜像之间以,分割'
        required: true
        default: 'debian:latest'
jobs:
  syncImages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        bash $GITHUB_WORKSPACE/scripts/copy-images.sh ${{ github.event.inputs.srcImage }}